title = "dweb.wiki"
description = "Distributed Networks Knowledgebase"


# Theme configuration goes here
[theme]
# Theme Name decides which theme to load
name = "bulmat"

# Global options of this wiki
[options]
output_directory = "./docs/"
pages_directory = "./pages/"

# Plugins
[plugins]
# Decides what plugins are activated or not
activated = ["markdown", "autolinker"]
